//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APT_ArchV03.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Caw
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Caw()
        {
            this.CawJobs = new HashSet<CawJob>();
        }
    
        public int caw_id { get; set; }
        [Required]
        [Display(Name = "Name")]
        public string caw_name { get; set; }

        [Display(Name = "Client")]
        public string caw_client { get; set; }

        [Display(Name = "Partner")]
        public string caw_partner { get; set; }

        [Display(Name = "Manager")]
        public string caw_manager { get; set; }

        [Display(Name = "Office")]
        public string caw_office { get; set; }

        [Required]
        [Display(Name = "Statement date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> caw_stdate { get; set; }

        [Display(Name = "Report date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> caw_reldate { get; set; }

        [Display(Name = "Delivery date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> caw_dldate { get; set; }

        [Display(Name = "Arch date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> caw_archdate { get; set; }

        [Display(Name = "Filename")]
        public string caw_fname { get; set; }

        [Display(Name = "Notes")]
        public string caw_notes { get; set; }

        [Display(Name = "Status")]
        public Nullable<int> caw_status { get; set; }

        public System.DateTime caw_crdate { get; set; }

        [Display(Name = "Created by")]
        public string caw_usrcreator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "CawJob")]
        public virtual ICollection<CawJob> CawJobs { get; set; }
    }

    
}
