//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APT_ArchV03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CawJob
    {
        public int cawjob_id { get; set; }
        public int caw_id { get; set; }
        public string cawjob_jc { get; set; }
        public string cawjob_jn { get; set; }
    
        public virtual Caw Caw { get; set; }
    }
}
