//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APT_ArchV03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavJob
    {
        public int id { get; set; }
        public string Client { get; set; }
        public string Job_Name { get; set; }
        public string Job_Code { get; set; }
        public string Region { get; set; }
        public string Project_Manager { get; set; }
        public string Partner_Gestore { get; set; }
        public Nullable<int> Time_Capacity { get; set; }
        public string Job_Status { get; set; }
        public string Type { get; set; }
    
        public virtual NavClient NavClient { get; set; }
    }
}
