//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APT_ArchV03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavResource
    {
        public int id { get; set; }
        public string Resource_Name { get; set; }
        public string Role { get; set; }
        public string Location { get; set; }
        public string Staff_NO { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        public string Region { get; set; }
        public string User_name { get; set; }
        public string Active { get; set; }
        public string Email { get; set; }
        public Nullable<int> Resource_Level { get; set; }
    }
}
