//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APT_ArchV03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VNavClient
    {
        public int ID { get; set; }
        public string Client_Name { get; set; }
        public string Client_ID { get; set; }
    }
}
